# Generated by Django 2.0.3 on 2018-03-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Notif',
        ),
    ]
