# Generated by Django 2.0.3 on 2018-03-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee_pay',
            name='trans_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
