# Generated by Django 2.0.3 on 2018-03-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='pass_word',
        ),
    ]
