# Generated by Django 2.0.3 on 2018-03-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180331_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee_pay',
            name='trans_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
