# Generated by Django 2.0.3 on 2018-03-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180328_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wearethere',
        ),
    ]
