# Generated by Django 2.0.3 on 2018-03-31 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180331_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee_pay',
            name='card_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
